name: Crowdin Sync
on:
  push:
    branches: [ main ]
    paths: 
      - 'module/webui/locales/strings/*.xml'
  workflow_dispatch:

jobs:
  sync-translations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crowdin/github-action@v1
        with:
          upload_sources: true
          upload_translations: true
          download_translations: true
          skip_untranslated_files: true

          create_pull_request: true
          localization_branch_name: crowdin_branch
          pull_request_labels: 'enhancement, documentation'
          pull_request_title: '[Translation] Update translation from Crowdin'

          config: 'crowdin.yml'
          crowdin_branch_name: main

        env:
         GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
         CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
         CROWDIN_API_TOKEN: ${{ secrets.CROWDIN_API_TOKEN }}
